#!/usr/bin/env python3
"""Load a caller repo's .claude/project-config.yml and emit KEY=VALUE pairs.

Reads the YAML config from the path given on the command line (typically
$GITHUB_WORKSPACE/.claude/project-config.yml), merges it with workflow-level
defaults, validates the shape, and prints the resolved values as
KEY=VALUE lines suitable for >> "$GITHUB_ENV" or eval.

If the config file is missing, embedded defaults are emitted unchanged so a
caller can opt out of config-driven mode by not creating the file (backward
compatible — matches the pre-config-layer hardcoded direct_push behavior).

Malformed YAML or unknown fields are fatal: we surface the error rather than
silently fall back, because a silently-wrong terminal_action would be much
worse than a failing run.

Usage:
    load-project-config.py [PATH] [--default-base-branch BRANCH]

Exits non-zero on YAML parse error, schema violation, or invalid enum value.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shlex
import sys
from pathlib import Path
from typing import Any

try:
    import yaml  # type: ignore[import-not-found]
except ImportError:
    sys.stderr.write(
        "ERROR: PyYAML is required. Install with: pip install pyyaml\n"
    )
    sys.exit(2)


VALID_TERMINAL_ACTIONS = {"direct_push", "merge_request"}
VALID_ON_CONFLICT = {"fail", "rebase"}
VALID_COLLISION = {"append_timestamp", "fail"}

EMBEDDED_DEFAULTS: dict[str, Any] = {
    "git": {
        "base_branch": "dev",
        "terminal": {
            "action": "direct_push",
            "on_conflict": "fail",
            "branch": {
                "pattern": "{base}_{ticket_num}",
                "on_collision": "append_timestamp",
            },
            "mr": {
                "title_template": "Fix #{ticket_num}: {title}",
                "squash": False,
                "remove_source_branch": True,
                "assignees": [],
                "reviewers": [],
            },
        },
    },
    "ticket_number": {
        "source_order": ["title", "github"],
        "title_regex": r"^\[?(\d+)\]?",
    },
    "commit": {
        "title_template": "fix #{ticket_num}: {title}",
        "body_template": (
            "Auto-generated by Claude.\nSource: {repo}#{github_num}\nRun: {run_url}\n"
        ),
    },
    "notification": {
        "success_label": "pushed",
        "conflict_label": "conflict",
        "success_comment_template": "direct_push_success",
    },
}


def deep_merge(base: dict[str, Any], override: dict[str, Any]) -> dict[str, Any]:
    """Recursively merge override into base, returning a new dict.

    Lists and scalars are replaced wholesale; only dicts are merged.
    """
    out = dict(base)
    for k, v in override.items():
        if isinstance(v, dict) and isinstance(out.get(k), dict):
            out[k] = deep_merge(out[k], v)
        else:
            out[k] = v
    return out


def validate(cfg: dict[str, Any]) -> None:
    """Fail-fast on unknown or invalid values. No silent coercion."""
    action = cfg["git"]["terminal"]["action"]
    if action not in VALID_TERMINAL_ACTIONS:
        sys.stderr.write(
            f"ERROR: git.terminal.action='{action}' is not one of "
            f"{sorted(VALID_TERMINAL_ACTIONS)}\n"
        )
        sys.exit(3)

    on_conflict = cfg["git"]["terminal"].get("on_conflict", "fail")
    if on_conflict not in VALID_ON_CONFLICT:
        sys.stderr.write(
            f"ERROR: git.terminal.on_conflict='{on_conflict}' is not one of "
            f"{sorted(VALID_ON_CONFLICT)}\n"
        )
        sys.exit(3)

    collision = cfg["git"]["terminal"]["branch"].get("on_collision", "append_timestamp")
    if collision not in VALID_COLLISION:
        sys.stderr.write(
            f"ERROR: git.terminal.branch.on_collision='{collision}' is not one of "
            f"{sorted(VALID_COLLISION)}\n"
        )
        sys.exit(3)

    regex = cfg["ticket_number"]["title_regex"]
    try:
        re.compile(regex)
    except re.error as exc:
        sys.stderr.write(
            f"ERROR: ticket_number.title_regex is not a valid regex: {exc}\n"
        )
        sys.exit(3)


def emit_env(cfg: dict[str, Any]) -> list[str]:
    """Flatten the resolved config to shell-safe KEY=VALUE lines.

    Booleans become 'true'/'false'; lists become space-separated strings;
    multiline scalars are JSON-encoded so the consumer can unmarshal safely
    without worrying about newlines.
    """
    g = cfg["git"]
    t = g["terminal"]
    b = t["branch"]
    m = t["mr"]
    tn = cfg["ticket_number"]
    c = cfg["commit"]
    n = cfg["notification"]

    def _bool(x: bool) -> str:
        return "true" if x else "false"

    lines: list[str] = []
    lines.append(f"BASE_BRANCH={shlex.quote(g['base_branch'])}")
    lines.append(f"TERMINAL_ACTION={shlex.quote(t['action'])}")
    lines.append(f"ON_CONFLICT={shlex.quote(t.get('on_conflict', 'fail'))}")
    lines.append(f"BRANCH_PATTERN={shlex.quote(b['pattern'])}")
    lines.append(f"BRANCH_ON_COLLISION={shlex.quote(b.get('on_collision', 'append_timestamp'))}")
    lines.append(f"MR_TITLE_TEMPLATE={shlex.quote(m['title_template'])}")
    lines.append(f"MR_SQUASH={_bool(m.get('squash', False))}")
    lines.append(f"MR_REMOVE_SOURCE_BRANCH={_bool(m.get('remove_source_branch', True))}")
    lines.append(f"MR_ASSIGNEES={shlex.quote(' '.join(m.get('assignees', [])))}")
    lines.append(f"MR_REVIEWERS={shlex.quote(' '.join(m.get('reviewers', [])))}")
    lines.append(f"TICKET_SOURCE_ORDER={shlex.quote(' '.join(tn['source_order']))}")
    lines.append(f"TICKET_TITLE_REGEX={shlex.quote(tn['title_regex'])}")
    lines.append(f"COMMIT_TITLE_TEMPLATE={shlex.quote(c['title_template'])}")
    # Body template can contain newlines; JSON-encode so the consumer can decode
    # without losing them. Workflows that need it should do
    # `python3 -c "import json,os,sys; print(json.loads(os.environ['COMMIT_BODY_TEMPLATE_JSON']))"`
    lines.append(f"COMMIT_BODY_TEMPLATE_JSON={shlex.quote(json.dumps(c['body_template']))}")
    lines.append(f"SUCCESS_LABEL={shlex.quote(n['success_label'])}")
    lines.append(f"CONFLICT_LABEL={shlex.quote(n.get('conflict_label', 'conflict'))}")
    lines.append(f"SUCCESS_COMMENT_TEMPLATE={shlex.quote(n.get('success_comment_template', 'direct_push_success'))}")
    return lines


def load(path: Path, default_base_branch: str | None) -> dict[str, Any]:
    defaults = json.loads(json.dumps(EMBEDDED_DEFAULTS))  # deep copy
    if default_base_branch:
        defaults["git"]["base_branch"] = default_base_branch

    if not path.exists():
        sys.stderr.write(
            f"note: no project-config at {path}; using embedded defaults\n"
        )
        return defaults

    try:
        with open(path, "r", encoding="utf-8") as fh:
            raw = yaml.safe_load(fh) or {}
    except yaml.YAMLError as exc:
        sys.stderr.write(f"ERROR: failed to parse YAML at {path}: {exc}\n")
        sys.exit(3)
    except OSError as exc:
        sys.stderr.write(f"ERROR: failed to read {path}: {exc}\n")
        sys.exit(3)

    if not isinstance(raw, dict):
        sys.stderr.write(
            f"ERROR: {path} must be a mapping at top level (got {type(raw).__name__})\n"
        )
        sys.exit(3)

    return deep_merge(defaults, raw)


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "config_path",
        nargs="?",
        default=".claude/project-config.yml",
        help="Path to project-config.yml (default: .claude/project-config.yml)",
    )
    p.add_argument(
        "--default-base-branch",
        default=None,
        help="Fallback base_branch when config omits it (e.g. value of workflow input)",
    )
    args = p.parse_args()

    cfg = load(Path(args.config_path), args.default_base_branch)
    validate(cfg)

    for line in emit_env(cfg):
        print(line)
    return 0


if __name__ == "__main__":
    sys.exit(main())
